#!/bin/sh
#
# FILE:  deploy.sh
#
# PURPOSE:
# Shell script to process Qt Designer .ui files
# into Python code, and concatenate and combine
# with develop_CamControl.py into the deployable 
# version CamControl.py
#
# REQUIRES: in path
# - pyside2-uic
# - perl
#

echo $'# FILE: CamControl.py ' > CamControl.py
echo $'# DO NOT EDIT THIS FILE IT IS AUTO-GENERATED ' >> CamControl.py
echo '# version 0.10 June 2020 by k0nichiwa ' >> CamControl.py
echo '# LICENSE:  This software package and portions of it can be freely modified, included in other software, and distributed ' >> CamControl.py
echo '# Source code available at: https://github.com/k0nichiwa/FreeCAD_CamControl \n' >> CamControl.py
echo $'import PySide\n' >> CamControl.py
pyside2-uic CamControlPanelUI.ui | perl replace_imports.pl >> CamControl.py
pyside2-uic StartGameControlDialogUI.ui | perl replace_imports.pl >> CamControl.py
cat develop_CamControl.py >> CamControl.py

