#!/bin/sh
#
# FILE:  deploy.sh
#
# PURPOSE:
# Shell script to process Qt Designer .ui files
# into Python code, and concatenate and combine
# with develop_CamControl.py into the deployable 
# version CamControl.py
#
# REQUIRES: in path
# - pyside2-uic
# - perl
#

echo $'# FILE: CamControl.py\n' > CamControl.py
echo $'# DO NOT EDIT THIS FILE IT IS AUTO-GENERATED\n' >> CamControl.py
echo $'import PySide\n' >> CamControl.py
pyside2-uic CamControlPanelUI.ui | perl replace_imports.pl >> CamControl.py
pyside2-uic StartGameControlDialogUI.ui | perl replace_imports.pl >> CamControl.py
cat develop_CamControl.py >> CamControl.py

